[package]
name = "axum-webserver"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
hyper = "1.6.0"
serde = "1.0.219"
tokio = { version = "1.47.1", features = ["full", "macros", "rt-multi-thread"] }
